services:
  autorestic:
    build:
      context: .
      dockerfile: Containerfile
    env_file: /srv/containers/storage/ssd/secrets/Autorestic.env
    volumes:
      - ./autorestic.yaml:/autorestic.yaml:ro
      - /srv/containers/storage/ssd:/srv/containers/storage/ssd:ro
      - /srv/containers/storage/hdd/media/photo:/srv/containers/storage/hdd/media/photo:ro