services:
  caddy-internal:
    build:
      context: .
      dockerfile: Containerfile
    user: "568"
    restart: unless-stopped
    command: "caddy run -c /Caddyfile"
    env_file: /srv/containers/storage/ssd/secrets/secrets.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./internal.Caddyfile:/Caddyfile
      - /srv/containers/storage/ssd/caddy/internal/config:/config
      - /srv/containers/storage/ssd/caddy/internal/data:/data
    depends_on:
      - garage
      - grafana
      - prometheus
      - prowlarr
      - qbittorrent
      - radarr
      - sabnzbd
      - slskd
      - sonarr
  caddy-external:
    build:
      context: .
      dockerfile: Containerfile
    user: "568"
    restart: unless-stopped
    command: "caddy run -c /Caddyfile"
    env_file: /srv/containers/storage/ssd/secrets/secrets.env
    ports:
      - "6996:6996"
      - "6997:6997"
    volumes:
      - ./external.Caddyfile:/Caddyfile
      - /srv/containers/storage/ssd/caddy/external/config:/config
      - /srv/containers/storage/ssd/caddy/external/data:/data
      - /srv/containers/storage/ssd/sharex:/sharex:ro
    depends_on:
      - audiobookshelf
      - freshrss
      - garage
      - home-assistant
      - komga
      - navidrome
      - overseerr
      - pathfinder
      - pinchflat
