services:
  prowlarr:
    image: ghcr.io/onedr0p/prowlarr-develop:1.12.2.4211
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - PROWLARR__PORT=80
    volumes:
      - /srv/containers/storage/ssd/prowlarr:/config:rw