services:
  radarr:
    image: ghcr.io/home-operations/radarr:5.26.2
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - RADARR__PORT=80
    volumes:
      - /srv/containers/storage/ssd/radarr:/config:rw
      - /srv/containers/storage/hdd/media:/media:rw
  prowlarr:
    image: ghcr.io/home-operations/prowlarr:1.37
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
      - PROWLARR__PORT=80
    volumes:
      - /srv/containers/storage/ssd/prowlarr:/config:rw
  sonarr:
    image: ghcr.io/home-operations/sonarr:4.0.15
    restart: unless-stopped
    user: "568"
    environment:
      - TZ=Europe/London
    volumes:
      - /srv/containers/storage/ssd/sonarr:/config:rw
      - /srv/containers/storage/hdd/media:/media:rw
