services:
  slskd:
    image: slskd/slskd:0.21.2
    restart: unless-stopped
    user: "568"
    ports:
      - 34000:34000
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /srv/containers/storage/ssd/slskd:/app:rw
      - /srv/containers/storage/hdd/media:/media:rw