services:
  slskd:
    image: slskd/slskd:0.20.0
    restart: unless-stopped
    user: "568"
    ports:
      - 34000:34000
    volumes:
      - /srv/containers/storage/ssd/slskd:/app:rw
      - /srv/containers/storage/hdd/media:/media:rw