metadata_dir = "/storage/config/meta"
data_dir = "/storage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "0.0.0.0:3901"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = ".s3.sams.wtf"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = ".site.s3.sams.wtf"
index = "index.html"

[admin]
api_bind_addr = "0.0.0.0:3903"
